### ISSUE TITLE
doesn't work on maximized windows

### ISSUE THREAD

**Issue by PDiracDelta** [jc00ke/move-to-next-monitor#3]
I've read about some more issues related to maximizing windows, but I think this wasn't mentioned yet:

On Xubuntu 16.04, it is not possible for me to move maximized windows. 

Also when running a fullscreen window (game opened with WINE) when moving to next monitor, the cursor focus is suddenly restricted to the next monitor (as it should) but the window itself remains on the current/previous monitor. 
Also, after switching back to that previous monitor to regain control over that fullscreen window, it becomes uncontrollable (as if the cursor focus still isn't on that monitor, though it really is. Can't click any buttons.)

**Comment by jc00ke** [comment]
Hi @PDiracDelta,

It's been almost 4 years... I hope you figured this out. Regardless, I don't use this anymore so I'm going to close this issue. If you've figured it out, let me know.
