### ISSUE TITLE
Shellcheck issues

### ISSUE THREAD

**Issue by ghost** [jc00ke/move-to-next-monitor#4]
Shellcheck output: http://ix.io/1O7F

Git patch: http://ix.io/107J

**Comment by ghost** [comment]
Since github edit buttons don't seem to work for me, the real link for the patch is: http://ix.io/1O7J

**Comment by jc00ke** [comment]
Shellcheck! Thanks, though that patch doesn't look right. 

Could you open a PR instead?

**Comment by jc00ke** [comment]
Ah, just saw your new comment, that looks right. I'll take a look shortly.

**Comment by ghost** [comment]
I cba to clone the repo. I really hate the way github works.

**Comment by jc00ke** [comment]
The patch doesn't cleanly check out. Is your patch based on the latest on `master`? I'd like for it to cleanly apply and to sign off as well.

**Comment by ghost** [comment]
The version I cloned and subsequently edited was 4040159af1982771b6d8ec417e503963270a40fb
