### ISSUE TITLE
With different resolutions, window is placed outside screen edge

### ISSUE THREAD

**Issue by ghost** [jc00ke/move-to-next-monitor#6]
**I tried setting up with my resolutions already like this:**
DVI-1: 1920x1080
DVI-2: 1024x768

What ended up happening when I ran the script is it moved the window to the big monitor (DVI-1) and resized it OK, but when I pressed it again it toggled it back to the small monitor (DVI-2) it moved the window off the screen edge.

**I was curious and tried setting them both to 1920x1080 and now it works as expected.**

**My guess is it does not work with different resolutions yet, or it does but it is broken.**

Still love the script though, I have it binded and working with equal resolutions on both monitors and I love it! Exactly what I needed... Thanks!

**Comment by jc00ke** [comment]
I think there's an opportunity for a fix. I'm without laptop for a while, care to give it a whirl?

**Comment by ghost** [comment]
I do know some _limited_ shell programming... But unfortunately this script is beyond my comprehension.

You will have to make the changes yourself.

**Comment by jc00ke** [comment]
I'd love to hack on this, but I don't have any time coming up. Hopefully in a few months when things have settled. I hope having equal resolutions isn't a pain for you.

**Comment by jc00ke** [comment]
I'm on i3 now and I'm not motivated to work on this. Closing for now, though would love to see a contribution to address the issue.
