### ISSUE TITLE
Readme isn't complete

### ISSUE THREAD

**Issue by iiw** [jc00ke/move-to-next-monitor#7]
Hello. Thanks for the script, it saved me a lot of time :)
But in different systems xorg apps can be not installed. Please add to the README required packages list.
Thank you.

**Comment by jc00ke** [comment]
I don't even use this myself anymore. If you open a PR with the list I'd be happy to merge it. Beyond that, I'm not going to put any effort into figuring out the dependencies.

I think it would help to have dependency checking built into the script, kinda like [checkfor](https://gist.github.com/montanaflynn/e1e754784749fd2aaca7). Care to add that as well?

**Comment by jc00ke** [comment]
Fixed by #8
